Fix validations and add notes.txt

diff --git a/cgiwork b/cgiwork
--- a/cgiwork
+++ b/cgiwork
@@ -1,10 +1,5 @@
 #!/bin/bash
 
-# Usar sed "s/$FIND/$REPLACE/g" quando possível para maior legitividade
-# Em hipótese alguma, o script deve falhar dentro do framework (comando 2>/dev/null || echo erro)
-# Incluir versão aqui também Ex:(0.1.5)
-# Usar cores (Função message)
-
 #######################################################################
 #                                                                     #
 #                               CGIWork                               #
@@ -12,8 +7,12 @@
 #  Description: Replace shell variables into an output file, keeping  #
 #               your output files and shell scripts separated.        #
 #                                                                     #
-#  Usage: cgiwork output_file                                         #
-#  Example: cgiwork templates/example.html                            #
+#  Usage: cgiwork "${ARRAY[@]}"                                       #
+#                                                                     #
+#  Important: The output file must be the first element of the array  #
+#  Example of array: ARRAY=("templates/example.html");                #
+#                    ARRAY+=("variable1=value1");                     #
+#                    ARRAY+=("variable2=value2");                     #
 #                                                                     #
 #  Author: LBezerril                                                  #
 #  To see the documentation, visit: github.com/LBezerril/CGIWork      #
@@ -25,6 +24,14 @@ KEY_VALUE_ARRAY=( "$@" );
 OUTPUT_FILE="${KEY_VALUE_ARRAY[0]}" && unset KEY_VALUE_ARRAY[0];
 MESSAGE_ERROR="CGIWork Error:";
 
+if [[ ! -f "$OUTPUT_FILE" ]]; then
+	echo "$MESSAGE_ERROR Output file does not exist! Be sure to pass the output file as the first element of the array.";
+	exit 1;
+elif [[ ! -r "$OUTPUT_FILE" ]]; then
+	echo "$MESSAGE_ERROR Output file is not readable!";
+	exit 1;
+fi;
+
 function replace_variables() {
 	for key_value in "${KEY_VALUE_ARRAY[@]}"; do
 		local key="$(echo "$key_value" | cut -d= -f1)"; #local key="$(echo "$key_value" | grep -o "^.[^=]*")";
@@ -35,20 +42,5 @@ function replace_variables() {
 	done;
 	cat "$OUTPUT_FILE" | sed "$sedexpression";
 }
-
-if [[ "$#" -lt 1 ]]; then
-	echo "$MESSAGE_ERROR Output file unspecified!";
-	exit 1;
-else
-	if [[ ! -f "$OUTPUT_FILE" ]]; then
-		echo "$MESSAGE_ERROR Output file does not exist!";
-		exit 1;
-	else
-		if [[ ! -r "$OUTPUT_FILE" ]]; then
-			echo "$MESSAGE_ERROR Output file is not readable!";
-			exit 1;
-		fi;
-	fi;
-fi;
 
 replace_variables;
