Refactoring

diff --git a/cgiwork b/cgiwork
--- a/cgiwork
+++ b/cgiwork
@@ -46,6 +46,17 @@ function is_running_interactivelly() {
 	if ! [ -t 0 ]; then return 1; fi;
 }
 
+function fail_if_file_is_invalid() {
+	# $1: file;
+	if [[ ! -f "$1" ]]; then
+		echo "$MESSAGE_ERROR Output file does not exist!";
+		exit 1;
+	elif [[ ! -r "$1" ]]; then
+		echo "$MESSAGE_ERROR Output file is not readable!";
+		exit 1;
+	fi;
+}
+
 TYPE="$(get_property type)";
 
 if ! $(is_expected_value $TYPE $EXPECTED_VALUES); then
