New option: Stdout to sed

diff --git a/scripts/cgiwork_plain b/scripts/cgiwork_plain
--- a/scripts/cgiwork_plain
+++ b/scripts/cgiwork_plain
@@ -1,13 +1,5 @@
 OUTPUT_FILE="$(get_property file)";
 
-if [[ ! -f "$OUTPUT_FILE" ]]; then
-	echo "$MESSAGE_ERROR Output file does not exist! Be sure to pass the output file as the first element of the array.";
-	exit 1;
-elif [[ ! -r "$OUTPUT_FILE" ]]; then
-	echo "$MESSAGE_ERROR Output file is not readable!";
-	exit 1;
-fi;
-
 function get_sedexpression_replace() {
 	for key_value in "${ARRAY[@]}"; do
 		local key="$(echo "$key_value" | cut -d= -f1)"; #local key="$(echo "$key_value" | grep -o "^.[^=]*")";
@@ -19,4 +11,17 @@ function get_sedexpression_replace() {
 	echo "$sedexpression";
 }
 
-cat "$OUTPUT_FILE" | sed "$(get_sedexpression_replace)";
+if var_is_null "$OUTPUT_FILE"; then
+	while read line; do
+		echo "$line";
+	done;
+else
+	if [[ ! -f "$OUTPUT_FILE" ]]; then
+		echo "$MESSAGE_ERROR Output file does not exist!";
+		exit 1;
+	elif [[ ! -r "$OUTPUT_FILE" ]]; then
+		echo "$MESSAGE_ERROR Output file is not readable!";
+		exit 1;
+	fi;
+	cat "$OUTPUT_FILE";
+fi | sed "$(get_sedexpression_replace)";
